/**
 * Initialize PWA features
 */
export function initPWA(): void {
  // PWA features are for browsers. In Capacitor native WebViews, service workers
  // can cause stale caching and blank screens after updates.
  // Note: window.Capacitor can exist on the web too, so check isNativePlatform().
  const w = window as any;
  const isNativeCapacitor = typeof window !== 'undefined'
    && !!w?.Capacitor
    && typeof w.Capacitor.isNativePlatform === 'function'
    && w.Capacitor.isNativePlatform();

  if (isNativeCapacitor) return;

  // Only register SW for production builds. In dev, SW caching can break HMR.
  if (!import.meta.env.PROD) {
    return;
  }

  // Register service worker (generated by vite-plugin-pwa).
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js').catch((err) => {
      console.error('[PWA] ServiceWorker registration failed:', err);
    });
  }

  // Check for updates periodically
  if ('serviceWorker' in navigator && navigator.serviceWorker.controller) {
    // Check for service worker updates every hour
    setInterval(() => {
      navigator.serviceWorker.getRegistration().then((registration) => {
        if (registration) {
          registration.update();
        }
      });
    }, 60 * 60 * 1000); // 1 hour
  }

  // Handle app install prompt
  let deferredPrompt: any;
  
  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    deferredPrompt = e;
    // You can show an install button here if needed
  });

  // Handle app installed
  window.addEventListener('appinstalled', () => {
    deferredPrompt = null;
  });

  // Handle service worker updates
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      // Optionally show a notification that app has been updated
      if (navigator.serviceWorker.controller) {
        console.log('[PWA] App has been updated');
      }
    });
  }
}
