/**
 * Initialize PWA features
 */
export function initPWA(): void {
  // PWA features are for browsers. In Capacitor native WebViews, service workers
  // can cause stale caching and blank screens after updates.
  // Note: window.Capacitor can exist on the web too, so check isNativePlatform().
  const w = window as any;
  const isNativeCapacitor = typeof window !== 'undefined'
    && !!w?.Capacitor
    && typeof w.Capacitor.isNativePlatform === 'function'
    && w.Capacitor.isNativePlatform();

  if (isNativeCapacitor) return;

  // Only register SW for production builds. In dev, SW caching can break HMR.
  if (!import.meta.env.PROD) {
    return;
  }

  // Register service worker (generated by vite-plugin-pwa).
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw.js').then((registration) => {
      console.log('[PWA] ServiceWorker registered successfully');
      
      // Check for updates immediately on registration
      if (registration) {
        console.log('[PWA] Checking for updates on startup...');
        registration.update();
      }
    }).catch((err) => {
      console.error('[PWA] ServiceWorker registration failed:', err);
    });
  }

  // Check for updates periodically and on visibility change
  const checkForUpdates = () => {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.getRegistration().then((registration) => {
        if (registration) {
          console.log('[PWA] Checking for updates...');
          registration.update();
        }
      });
    }
  };

  // Check for updates every 5 minutes (aggressive for faster updates)
  if ('serviceWorker' in navigator && navigator.serviceWorker.controller) {
    setInterval(checkForUpdates, 5 * 60 * 1000); // 5 minutes
  }

  // Check for updates when app becomes visible (user returns to tab)
  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) {
      checkForUpdates();
    }
  });

  // Check for updates when window gains focus
  window.addEventListener('focus', () => {
    checkForUpdates();
  });

  // Handle app install prompt
  let deferredPrompt: any;
  
  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault();
    deferredPrompt = e;
    // You can show an install button here if needed
  });

  // Handle app installed
  window.addEventListener('appinstalled', () => {
    deferredPrompt = null;
  });

  // Handle service worker updates - auto reload when new version detected
  if ('serviceWorker' in navigator) {
    let refreshing = false;
    
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      // New service worker has taken control - reload page automatically
      if (refreshing) return; // Prevent infinite reload loop
      
      refreshing = true;
      console.log('[PWA] New version detected, auto-reloading...');
      
      // Wait a tiny bit to ensure SW is fully active
      setTimeout(() => {
        window.location.reload();
      }, 100);
    });
    
    // Also listen for update notifications from the service worker
    navigator.serviceWorker.addEventListener('message', (event) => {
      if (event.data?.type === 'UPDATE_AVAILABLE') {
        console.log('[PWA] Update available, will reload on next activation');
      }
    });
  }
  
  // Register update handler for service worker registration
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.ready.then((registration) => {
      registration.addEventListener('updatefound', () => {
        const newWorker = registration.installing;
        if (newWorker) {
          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
              // New service worker installed and ready - skip waiting
              console.log('[PWA] New version installed, activating...');
              newWorker.postMessage({ type: 'SKIP_WAITING' });
            }
          });
        }
      });
    });
  }
}
